#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Mac-specific customizations
if [ -d /Users/sdh ]; then
  # The next line updates PATH for the Google Cloud SDK.
  source '/Users/sdh/local/opt/google-cloud-sdk/path.zsh.inc'

  # The next line enables shell command completion for gcloud.
  source '/Users/sdh/local/opt/google-cloud-sdk/completion.zsh.inc'

  PATH=$HOME/local/bin:$PATH
  export DYLD_LIBRARY_PATH=/Users/sdh/local/opt/rust/lib/rustlib/x86_64-apple-darwin/lib
fi
